=== Mitso98/xml/Lab-1/xml-lab1/newXMLDocument.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ENTITY My_loction "241 El-Haram st. Giza">

<!ELEMENT library (location,description,librarian,books)*>


<!ELEMENT location (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT librarian (#PCDATA)>


<!ELEMENT books (book*)>
<!ELEMENT book (title|author|year|price|chapters)*>
<!ATTLIST book
    category CDATA #IMPLIED
    isbn CDATA #REQUIRED
  >


<!ELEMENT title (#PCDATA)>

<!ELEMENT author (#PCDATA)>
<!ATTLIST author
    gander (M|F) "M"
  >

<!ELEMENT year (#PCDATA)>

<!ELEMENT price (#PCDATA)>

<!ELEMENT chapters (chapter)*>

<!ELEMENT chapter (title|summary|sections)*>
<!ATTLIST chapter
    id CDATA #REQUIRED 
  >


<!ELEMENT summary (#PCDATA)>


<!ELEMENT sections (#PCDATA)>

=== Mitso98/xml/Lab-1/xml-lab1/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "F:\iti\xml\Lab-1\xml-lab1\newXMLDocument.dtd">



<library>
    <location>&My_loction;</location>
    <description>Book Store</description>
    <librarian>Mostafa</librarian>
    
    <books>
        <book category="children" isbn="12">
            <title>Leage of legends</title>
            <author gander="M">J K. Rowling</author>
            <year>2023</year>
            <price>60</price>
            <chapters>
                <chapter id="324">
                    <title>One</title>
                    <summary>Summery of the chapter</summary>
                    <sections>
                        <![CDATA[ 
                            The first section containe &"'
                        
                        ]]>
                    </sections>
                </chapter>
                <chapter id="12">
                    <title>One</title>
                    <summary>Summery of the chapter</summary>
                    <sections>
                        <![CDATA[ 
                            The first section containe &"'
                        
                        ]]>
                    </sections>
                </chapter>
                <chapter id="3">
                    <title>One</title>
                    <summary>Summery of the chapter</summary>
                    <sections>
                        <![CDATA[ 
                            The first section containe &"'
                        
                        ]]>
                    </sections>
                </chapter>
            </chapters>
        </book>
        <book category="web" isbn="12">
            <title>Steal like an artisit</title>
            <author>Mostafa Ahmed</author>
            <year>1998</year>
            <price>100</price>
            <chapters>
                <chapter id="342">
                    <title>One</title>
                    <summary>Summery of the chapter</summary>
                    <sections>
                        <![CDATA[ 
                            The first section containe &"'
                        
                        ]]>
                    </sections>
                </chapter>
                <chapter id="43">
                    <title>One</title>
                    <summary>Summery of the chapter</summary>
                    <sections>
                        <![CDATA[ 
                            The first section containe &"'
                        
                        ]]>
                    </sections>
                </chapter>
                <chapter id="49">
                    <title>One</title>
                    <summary>Summery of the chapter</summary>
                    <sections>
                        <![CDATA[ 
                            The first section containe &"'
                        
                        ]]>
                    </sections>
                </chapter>
            </chapters>
            
        </book>
    </books>
</library>
